---
driver:
  name: ec2

driver_config:
  aws_ssh_key_id: chef-kitchen-test-aws
  instance_type: t2.medium

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: server
    run_list:
      - recipe[teamcity::database]
      - recipe[teamcity::server]
    attributes:
  - name: agent
    run_list:
      - recipe[teamcity::agent]
    attributes:
