name             'teamcity'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures teamcity-cookbook'
long_description 'Installs/Configures teamcity-cookbook'
version          '0.1.0'

depends 'java'
depends 'postgresql'
depends 'database'
depends 'apt'
depends 'tarball'
depends 'poise-service'
