name             'teamcity'
maintainer       'Chris Marchesi'
maintainer_email 'chrism@vancluevertech.com'
license          'MIT'
description      'Installs/Configures teamcity-cookbook'
long_description 'Installs/Configures teamcity-cookbook'
version          '1.1.5'

depends 'java'
depends 'postgresql'
depends 'database'
depends 'apt'
depends 'tarball'
depends 'poise-service'
depends 'sudo'
